language: ruby
rvm:
  - 2.2.3
before_install:
  - psql -c 'create database workshops_test;' -U postgres
  - cp config/database.yml.sample config/database.yml
addons:
  postgresql: '9.3'
cache: bundler
script:
  - RAILS_ENV=test rake db:create db:schema:load
  - RAILS_ENV=test bundle exec rspec
